
services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html           # live-edit CodeIgniter code
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html           # for static assets
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs:ro   # <─ new
    ports:
      - "8080:80"
      - "8443:443"          # HTTPS port
    depends_on:
      - app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"    # ← hostPort:containerPort

volumes:
  db_data:
